# Generated by Django 2.0.5 on 2018-07-10 01:41

from django.db import migrations, models
import django.db.models.deletion
import drugbank.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('action', drugbank.models.ListField(null=True)),
                ('knownAction', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.TextField(primary_key=True, serialize=False)),
                ('meshId', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField(null=True)),
                ('route', models.TextField(null=True)),
                ('strength', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('primaryDrugbankId', models.TextField(default='', primary_key=True, serialize=False)),
                ('alternativeDrugbankId', drugbank.models.ListField(default=[])),
                ('name', models.TextField()),
                ('casNumber', models.TextField(null=True)),
                ('unii', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('groups', drugbank.models.ListField(null=True)),
                ('toxicity', models.TextField(null=True)),
                ('metabolism', models.TextField(null=True)),
                ('halfLife', models.TextField(null=True)),
                ('proteinBinding', models.TextField(null=True)),
                ('volumeOfDistribution', models.TextField(null=True)),
                ('clearance', models.TextField(null=True)),
                ('affectedOrganisms', drugbank.models.ListField(null=True)),
                ('ahfsCodes', models.TextField(null=True)),
                ('pdbEntries', models.TextField(null=True)),
                ('fdaLabel', models.TextField(null=True)),
                ('msds', models.TextField(null=True)),
                ('foodInterations', drugbank.models.ListField(null=True)),
                ('sequences', drugbank.models.ListField(null=True)),
                ('enzymes', drugbank.models.ListField(null=True)),
                ('atcCodes', drugbank.models.ListField(null=True)),
                ('synonyms', drugbank.models.ListField(null=True)),
                ('classfication_description', models.TextField(null=True)),
                ('classfication_directParent', models.TextField(null=True)),
                ('classfication_kingdom', models.TextField(null=True)),
                ('classfication_superclass', models.TextField(null=True)),
                ('classfication_kls', models.TextField(null=True)),
                ('classfication_subclass', models.TextField(null=True)),
                ('classfication_alternativeParents', drugbank.models.ListField(null=True)),
                ('classfication_substituent', drugbank.models.ListField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug1_drugInteractions', to='drugbank.Drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug2_drugInteractions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Enzyme',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('action', drugbank.models.ListField(null=True)),
                ('knownAction', models.TextField(null=True)),
                ('drug', models.ManyToManyField(related_name='drug_enzymes', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField(null=True)),
                ('identifier', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_externalIdentifiers', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='GoClassifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ingredients', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_mixtures', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('smpdbId', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('enzymes', drugbank.models.ListField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_pathways', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('drugbankId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_asPathwayDrug', to='drugbank.Drug')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pathway_Drugs', to='drugbank.Pathway')),
            ],
        ),
        migrations.CreateModel(
            name='Pfam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polypeptide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField(default='')),
                ('source', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('generalFunction', models.TextField(null=True)),
                ('specificFunction', models.TextField(null=True)),
                ('geneName', models.TextField(null=True)),
                ('locus', models.TextField(null=True)),
                ('cellularLocation', models.TextField(null=True)),
                ('transmembraneRegions', models.TextField(null=True)),
                ('signalRegions', models.TextField(null=True)),
                ('theoreticalPi', models.TextField(null=True)),
                ('molecularWeight', models.TextField(null=True)),
                ('chromosomeLocation', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('organismNcbiTaxonomyId', models.TextField(null=True)),
                ('aminoAcidSequence', models.TextField(null=True)),
                ('geneSequence', models.TextField(null=True)),
                ('externalIdentifiers', models.TextField(null=True)),
                ('synonyms', drugbank.models.ListField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolypeptideExternalIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.TextField(null=True)),
                ('identifier', models.TextField(null=True)),
                ('polypeptide', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polypeptide_externalIdentifiers', to='drugbank.Polypeptide')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(null=True)),
                ('value', models.TextField(null=True)),
                ('source', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_properties', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('action', drugbank.models.ListField(null=True)),
                ('knownAction', models.TextField(null=True)),
                ('polypeptide', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seqence', models.IntegerField(default=-1, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs_reactions', to='drugbank.Drug')),
                ('left_element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs_asLeft_reactions', to='drugbank.Drug')),
                ('right_element', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drugs_asRight_reactions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionEnzyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('uniprotId', models.TextField(null=True)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reaction_enzymes', to='drugbank.Reaction')),
            ],
        ),
        migrations.CreateModel(
            name='Salt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugbankId', drugbank.models.ListField(null=True)),
                ('name', models.TextField(null=True)),
                ('unii', models.TextField(null=True)),
                ('casNumber', models.TextField(null=True)),
                ('inchikey', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_salt', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='SnpAdverseDrugReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.TextField(null=True)),
                ('geneSymbol', models.TextField(null=True)),
                ('uniprotId', models.TextField(null=True)),
                ('rsId', models.TextField(null=True)),
                ('allele', models.TextField(null=True)),
                ('adverseReaction', models.TextField(null=True)),
                ('definingChange', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('pubmedId', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_snpAdverseDrugReactions', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='SnpEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proteinName', models.TextField(null=True)),
                ('geneSymbol', models.TextField(null=True)),
                ('uniprotId', models.TextField(null=True)),
                ('rsId', models.TextField(null=True)),
                ('allele', models.TextField(null=True)),
                ('definingChange', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('pubmedId', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_snpEffects', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
                ('language', models.TextField(null=True)),
                ('coder', models.TextField(null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_synonym', to='drugbank.Drug')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('action', drugbank.models.ListField(null=True)),
                ('knownAction', models.TextField(null=True)),
                ('drug', models.ManyToManyField(related_name='drug_targets', to='drugbank.Drug')),
                ('polypeptide', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.TextField(default='', primary_key=True, serialize=False)),
                ('name', models.TextField(null=True)),
                ('organism', models.TextField(null=True)),
                ('action', drugbank.models.ListField(null=True)),
                ('knownAction', models.TextField(null=True)),
                ('drug', models.ManyToManyField(related_name='drug_transporters', to='drugbank.Drug')),
                ('polypeptide', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide')),
            ],
        ),
        migrations.AddField(
            model_name='pfam',
            name='polypeptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polypeptide_pfams', to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='goclassifier',
            name='polypeptide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='polypeptide_goClassifiers', to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='enzyme',
            name='polypeptide',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide'),
        ),
        migrations.AddField(
            model_name='dosage',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_dosages', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='category',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='drug_categories', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='drug',
            field=models.ManyToManyField(related_name='drug_carriers', to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='polypeptide',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drugbank.Polypeptide'),
        ),
    ]
